// Code generated by ogen, DO NOT EDIT.

package api

import (
	"io"
	"time"
)

type CreateUserApplicationJSON User

func (*CreateUserApplicationJSON) createUserReq() {}

type CreateUserApplicationXWwwFormUrlencoded User

func (*CreateUserApplicationXWwwFormUrlencoded) createUserReq() {}

type CreateUserReqEmptyBody struct{}

func (*CreateUserReqEmptyBody) createUserReq() {}

// CreateUsersWithListInputDef is default response for CreateUsersWithListInput operation.
type CreateUsersWithListInputDef struct {
	StatusCode int
}

// GetStatusCode returns the value of StatusCode.
func (s *CreateUsersWithListInputDef) GetStatusCode() int {
	return s.StatusCode
}

// SetStatusCode sets the value of StatusCode.
func (s *CreateUsersWithListInputDef) SetStatusCode(val int) {
	s.StatusCode = val
}

func (*CreateUsersWithListInputDef) createUsersWithListInputRes() {}

// DeleteUserBadRequest is response for DeleteUser operation.
type DeleteUserBadRequest struct{}

func (*DeleteUserBadRequest) deleteUserRes() {}

// DeleteUserNotFound is response for DeleteUser operation.
type DeleteUserNotFound struct{}

func (*DeleteUserNotFound) deleteUserRes() {}

// DeleteUserOK is response for DeleteUser operation.
type DeleteUserOK struct{}

func (*DeleteUserOK) deleteUserRes() {}

// GetUserByNameBadRequest is response for GetUserByName operation.
type GetUserByNameBadRequest struct{}

func (*GetUserByNameBadRequest) getUserByNameRes() {}

// GetUserByNameNotFound is response for GetUserByName operation.
type GetUserByNameNotFound struct{}

func (*GetUserByNameNotFound) getUserByNameRes() {}

// LoginUserBadRequest is response for LoginUser operation.
type LoginUserBadRequest struct{}

func (*LoginUserBadRequest) loginUserRes() {}

type LoginUserOKApplicationXML struct {
	Data io.Reader
}

// Read reads data from the Data reader.
//
// Kept to satisfy the io.Reader interface.
func (s LoginUserOKApplicationXML) Read(p []byte) (n int, err error) {
	if s.Data == nil {
		return 0, io.EOF
	}
	return s.Data.Read(p)
}

// LoginUserOKApplicationXMLHeaders wraps LoginUserOKApplicationXML with response headers.
type LoginUserOKApplicationXMLHeaders struct {
	XExpiresAfter OptDateTime
	XRateLimit    OptInt32
	Response      LoginUserOKApplicationXML
}

// GetXExpiresAfter returns the value of XExpiresAfter.
func (s *LoginUserOKApplicationXMLHeaders) GetXExpiresAfter() OptDateTime {
	return s.XExpiresAfter
}

// GetXRateLimit returns the value of XRateLimit.
func (s *LoginUserOKApplicationXMLHeaders) GetXRateLimit() OptInt32 {
	return s.XRateLimit
}

// GetResponse returns the value of Response.
func (s *LoginUserOKApplicationXMLHeaders) GetResponse() LoginUserOKApplicationXML {
	return s.Response
}

// SetXExpiresAfter sets the value of XExpiresAfter.
func (s *LoginUserOKApplicationXMLHeaders) SetXExpiresAfter(val OptDateTime) {
	s.XExpiresAfter = val
}

// SetXRateLimit sets the value of XRateLimit.
func (s *LoginUserOKApplicationXMLHeaders) SetXRateLimit(val OptInt32) {
	s.XRateLimit = val
}

// SetResponse sets the value of Response.
func (s *LoginUserOKApplicationXMLHeaders) SetResponse(val LoginUserOKApplicationXML) {
	s.Response = val
}

func (*LoginUserOKApplicationXMLHeaders) loginUserRes() {}

// LoginUserOKHeaders wraps string with response headers.
type LoginUserOKHeaders struct {
	XExpiresAfter OptDateTime
	XRateLimit    OptInt32
	Response      string
}

// GetXExpiresAfter returns the value of XExpiresAfter.
func (s *LoginUserOKHeaders) GetXExpiresAfter() OptDateTime {
	return s.XExpiresAfter
}

// GetXRateLimit returns the value of XRateLimit.
func (s *LoginUserOKHeaders) GetXRateLimit() OptInt32 {
	return s.XRateLimit
}

// GetResponse returns the value of Response.
func (s *LoginUserOKHeaders) GetResponse() string {
	return s.Response
}

// SetXExpiresAfter sets the value of XExpiresAfter.
func (s *LoginUserOKHeaders) SetXExpiresAfter(val OptDateTime) {
	s.XExpiresAfter = val
}

// SetXRateLimit sets the value of XRateLimit.
func (s *LoginUserOKHeaders) SetXRateLimit(val OptInt32) {
	s.XRateLimit = val
}

// SetResponse sets the value of Response.
func (s *LoginUserOKHeaders) SetResponse(val string) {
	s.Response = val
}

func (*LoginUserOKHeaders) loginUserRes() {}

// LogoutUserDef is default response for LogoutUser operation.
type LogoutUserDef struct {
	StatusCode int
}

// GetStatusCode returns the value of StatusCode.
func (s *LogoutUserDef) GetStatusCode() int {
	return s.StatusCode
}

// SetStatusCode sets the value of StatusCode.
func (s *LogoutUserDef) SetStatusCode(val int) {
	s.StatusCode = val
}

// NewOptDate returns new OptDate with value set to v.
func NewOptDate(v time.Time) OptDate {
	return OptDate{
		Value: v,
		Set:   true,
	}
}

// OptDate is optional time.Time.
type OptDate struct {
	Value time.Time
	Set   bool
}

// IsSet returns true if OptDate was set.
func (o OptDate) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptDate) Reset() {
	var v time.Time
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptDate) SetTo(v time.Time) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptDate) Get() (v time.Time, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptDate) Or(d time.Time) time.Time {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptDateTime returns new OptDateTime with value set to v.
func NewOptDateTime(v time.Time) OptDateTime {
	return OptDateTime{
		Value: v,
		Set:   true,
	}
}

// OptDateTime is optional time.Time.
type OptDateTime struct {
	Value time.Time
	Set   bool
}

// IsSet returns true if OptDateTime was set.
func (o OptDateTime) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptDateTime) Reset() {
	var v time.Time
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptDateTime) SetTo(v time.Time) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptDateTime) Get() (v time.Time, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptDateTime) Or(d time.Time) time.Time {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptInt32 returns new OptInt32 with value set to v.
func NewOptInt32(v int32) OptInt32 {
	return OptInt32{
		Value: v,
		Set:   true,
	}
}

// OptInt32 is optional int32.
type OptInt32 struct {
	Value int32
	Set   bool
}

// IsSet returns true if OptInt32 was set.
func (o OptInt32) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptInt32) Reset() {
	var v int32
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptInt32) SetTo(v int32) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptInt32) Get() (v int32, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptInt32) Or(d int32) int32 {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptInt64 returns new OptInt64 with value set to v.
func NewOptInt64(v int64) OptInt64 {
	return OptInt64{
		Value: v,
		Set:   true,
	}
}

// OptInt64 is optional int64.
type OptInt64 struct {
	Value int64
	Set   bool
}

// IsSet returns true if OptInt64 was set.
func (o OptInt64) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptInt64) Reset() {
	var v int64
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptInt64) SetTo(v int64) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptInt64) Get() (v int64, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptInt64) Or(d int64) int64 {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptString returns new OptString with value set to v.
func NewOptString(v string) OptString {
	return OptString{
		Value: v,
		Set:   true,
	}
}

// OptString is optional string.
type OptString struct {
	Value string
	Set   bool
}

// IsSet returns true if OptString was set.
func (o OptString) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptString) Reset() {
	var v string
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptString) SetTo(v string) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptString) Get() (v string, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptString) Or(d string) string {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

type UpdateUserApplicationJSON User

func (*UpdateUserApplicationJSON) updateUserReq() {}

type UpdateUserApplicationXWwwFormUrlencoded User

func (*UpdateUserApplicationXWwwFormUrlencoded) updateUserReq() {}

// UpdateUserDef is default response for UpdateUser operation.
type UpdateUserDef struct {
	StatusCode int
}

// GetStatusCode returns the value of StatusCode.
func (s *UpdateUserDef) GetStatusCode() int {
	return s.StatusCode
}

// SetStatusCode sets the value of StatusCode.
func (s *UpdateUserDef) SetStatusCode(val int) {
	s.StatusCode = val
}

type UpdateUserReqEmptyBody struct{}

func (*UpdateUserReqEmptyBody) updateUserReq() {}

// Ref: #/components/schemas/User
type User struct {
	ID         OptInt64  `json:"id"`
	Nickname   OptString `json:"nickname"`
	Name       OptString `json:"name"`
	Surname    OptString `json:"surname"`
	HashedPass OptString `json:"hashedPass"`
	UserStatus OptString `json:"userStatus"`
	Date       OptDate   `json:"date"`
}

// GetID returns the value of ID.
func (s *User) GetID() OptInt64 {
	return s.ID
}

// GetNickname returns the value of Nickname.
func (s *User) GetNickname() OptString {
	return s.Nickname
}

// GetName returns the value of Name.
func (s *User) GetName() OptString {
	return s.Name
}

// GetSurname returns the value of Surname.
func (s *User) GetSurname() OptString {
	return s.Surname
}

// GetHashedPass returns the value of HashedPass.
func (s *User) GetHashedPass() OptString {
	return s.HashedPass
}

// GetUserStatus returns the value of UserStatus.
func (s *User) GetUserStatus() OptString {
	return s.UserStatus
}

// GetDate returns the value of Date.
func (s *User) GetDate() OptDate {
	return s.Date
}

// SetID sets the value of ID.
func (s *User) SetID(val OptInt64) {
	s.ID = val
}

// SetNickname sets the value of Nickname.
func (s *User) SetNickname(val OptString) {
	s.Nickname = val
}

// SetName sets the value of Name.
func (s *User) SetName(val OptString) {
	s.Name = val
}

// SetSurname sets the value of Surname.
func (s *User) SetSurname(val OptString) {
	s.Surname = val
}

// SetHashedPass sets the value of HashedPass.
func (s *User) SetHashedPass(val OptString) {
	s.HashedPass = val
}

// SetUserStatus sets the value of UserStatus.
func (s *User) SetUserStatus(val OptString) {
	s.UserStatus = val
}

// SetDate sets the value of Date.
func (s *User) SetDate(val OptDate) {
	s.Date = val
}

func (*User) createUsersWithListInputRes() {}
func (*User) getUserByNameRes()            {}

// UserStatusCode wraps User with StatusCode.
type UserStatusCode struct {
	StatusCode int
	Response   User
}

// GetStatusCode returns the value of StatusCode.
func (s *UserStatusCode) GetStatusCode() int {
	return s.StatusCode
}

// GetResponse returns the value of Response.
func (s *UserStatusCode) GetResponse() User {
	return s.Response
}

// SetStatusCode sets the value of StatusCode.
func (s *UserStatusCode) SetStatusCode(val int) {
	s.StatusCode = val
}

// SetResponse sets the value of Response.
func (s *UserStatusCode) SetResponse(val User) {
	s.Response = val
}
