// Code generated by ogen, DO NOT EDIT.

package api

import (
	"bytes"
	"io"
	"mime"
	"net/http"
	"time"

	"github.com/go-faster/errors"
	"github.com/go-faster/jx"

	"github.com/ogen-go/ogen/conv"
	"github.com/ogen-go/ogen/ogenerrors"
	"github.com/ogen-go/ogen/uri"
	"github.com/ogen-go/ogen/validate"
)

func decodeCreateUserResponse(resp *http.Response) (res *UserStatusCode, _ error) {
	// Default response.
	res, err := func() (res *UserStatusCode, err error) {
		ct, _, err := mime.ParseMediaType(resp.Header.Get("Content-Type"))
		if err != nil {
			return res, errors.Wrap(err, "parse media type")
		}
		switch {
		case ct == "application/json":
			buf, err := io.ReadAll(resp.Body)
			if err != nil {
				return res, err
			}
			d := jx.DecodeBytes(buf)

			var response User
			if err := func() error {
				if err := response.Decode(d); err != nil {
					return err
				}
				if err := d.Skip(); err != io.EOF {
					return errors.New("unexpected trailing data")
				}
				return nil
			}(); err != nil {
				err = &ogenerrors.DecodeBodyError{
					ContentType: ct,
					Body:        buf,
					Err:         err,
				}
				return res, err
			}
			return &UserStatusCode{
				StatusCode: resp.StatusCode,
				Response:   response,
			}, nil
		default:
			return res, validate.InvalidContentType(ct)
		}
	}()
	if err != nil {
		return res, errors.Wrapf(err, "default (code %d)", resp.StatusCode)
	}
	return res, nil
}

func decodeCreateUsersWithListInputResponse(resp *http.Response) (res CreateUsersWithListInputRes, _ error) {
	switch resp.StatusCode {
	case 200:
		// Code 200.
		ct, _, err := mime.ParseMediaType(resp.Header.Get("Content-Type"))
		if err != nil {
			return res, errors.Wrap(err, "parse media type")
		}
		switch {
		case ct == "application/json":
			buf, err := io.ReadAll(resp.Body)
			if err != nil {
				return res, err
			}
			d := jx.DecodeBytes(buf)

			var response User
			if err := func() error {
				if err := response.Decode(d); err != nil {
					return err
				}
				if err := d.Skip(); err != io.EOF {
					return errors.New("unexpected trailing data")
				}
				return nil
			}(); err != nil {
				err = &ogenerrors.DecodeBodyError{
					ContentType: ct,
					Body:        buf,
					Err:         err,
				}
				return res, err
			}
			return &response, nil
		default:
			return res, validate.InvalidContentType(ct)
		}
	}
	// Default response.
	res, err := func() (res CreateUsersWithListInputRes, err error) {
		return &CreateUsersWithListInputDef{
			StatusCode: resp.StatusCode,
		}, nil
	}()
	if err != nil {
		return res, errors.Wrapf(err, "default (code %d)", resp.StatusCode)
	}
	return res, nil
}

func decodeDeleteUserResponse(resp *http.Response) (res DeleteUserRes, _ error) {
	switch resp.StatusCode {
	case 200:
		// Code 200.
		return &DeleteUserOK{}, nil
	case 400:
		// Code 400.
		return &DeleteUserBadRequest{}, nil
	case 404:
		// Code 404.
		return &DeleteUserNotFound{}, nil
	}
	return res, validate.UnexpectedStatusCode(resp.StatusCode)
}

func decodeGetUserByNameResponse(resp *http.Response) (res GetUserByNameRes, _ error) {
	switch resp.StatusCode {
	case 200:
		// Code 200.
		ct, _, err := mime.ParseMediaType(resp.Header.Get("Content-Type"))
		if err != nil {
			return res, errors.Wrap(err, "parse media type")
		}
		switch {
		case ct == "application/json":
			buf, err := io.ReadAll(resp.Body)
			if err != nil {
				return res, err
			}
			d := jx.DecodeBytes(buf)

			var response User
			if err := func() error {
				if err := response.Decode(d); err != nil {
					return err
				}
				if err := d.Skip(); err != io.EOF {
					return errors.New("unexpected trailing data")
				}
				return nil
			}(); err != nil {
				err = &ogenerrors.DecodeBodyError{
					ContentType: ct,
					Body:        buf,
					Err:         err,
				}
				return res, err
			}
			return &response, nil
		default:
			return res, validate.InvalidContentType(ct)
		}
	case 400:
		// Code 400.
		return &GetUserByNameBadRequest{}, nil
	case 404:
		// Code 404.
		return &GetUserByNameNotFound{}, nil
	}
	return res, validate.UnexpectedStatusCode(resp.StatusCode)
}

func decodeLoginUserResponse(resp *http.Response) (res LoginUserRes, _ error) {
	switch resp.StatusCode {
	case 200:
		// Code 200.
		ct, _, err := mime.ParseMediaType(resp.Header.Get("Content-Type"))
		if err != nil {
			return res, errors.Wrap(err, "parse media type")
		}
		switch {
		case ct == "application/json":
			buf, err := io.ReadAll(resp.Body)
			if err != nil {
				return res, err
			}
			d := jx.DecodeBytes(buf)

			var response string
			if err := func() error {
				v, err := d.Str()
				response = string(v)
				if err != nil {
					return err
				}
				if err := d.Skip(); err != io.EOF {
					return errors.New("unexpected trailing data")
				}
				return nil
			}(); err != nil {
				err = &ogenerrors.DecodeBodyError{
					ContentType: ct,
					Body:        buf,
					Err:         err,
				}
				return res, err
			}
			var wrapper LoginUserOKHeaders
			wrapper.Response = response
			h := uri.NewHeaderDecoder(resp.Header)
			// Parse "X-Expires-After" header.
			{
				cfg := uri.HeaderParameterDecodingConfig{
					Name:    "X-Expires-After",
					Explode: false,
				}
				if err := func() error {
					if err := h.HasParam(cfg); err == nil {
						if err := h.DecodeParam(cfg, func(d uri.Decoder) error {
							var wrapperDotXExpiresAfterVal time.Time
							if err := func() error {
								val, err := d.DecodeValue()
								if err != nil {
									return err
								}

								c, err := conv.ToDateTime(val)
								if err != nil {
									return err
								}

								wrapperDotXExpiresAfterVal = c
								return nil
							}(); err != nil {
								return err
							}
							wrapper.XExpiresAfter.SetTo(wrapperDotXExpiresAfterVal)
							return nil
						}); err != nil {
							return err
						}
					}
					return nil
				}(); err != nil {
					return res, errors.Wrap(err, "parse X-Expires-After header")
				}
			}
			// Parse "X-Rate-Limit" header.
			{
				cfg := uri.HeaderParameterDecodingConfig{
					Name:    "X-Rate-Limit",
					Explode: false,
				}
				if err := func() error {
					if err := h.HasParam(cfg); err == nil {
						if err := h.DecodeParam(cfg, func(d uri.Decoder) error {
							var wrapperDotXRateLimitVal int32
							if err := func() error {
								val, err := d.DecodeValue()
								if err != nil {
									return err
								}

								c, err := conv.ToInt32(val)
								if err != nil {
									return err
								}

								wrapperDotXRateLimitVal = c
								return nil
							}(); err != nil {
								return err
							}
							wrapper.XRateLimit.SetTo(wrapperDotXRateLimitVal)
							return nil
						}); err != nil {
							return err
						}
					}
					return nil
				}(); err != nil {
					return res, errors.Wrap(err, "parse X-Rate-Limit header")
				}
			}
			return &wrapper, nil
		case ct == "application/xml":
			reader := resp.Body
			b, err := io.ReadAll(reader)
			if err != nil {
				return res, err
			}

			response := LoginUserOKApplicationXML{Data: bytes.NewReader(b)}
			var wrapper LoginUserOKApplicationXMLHeaders
			wrapper.Response = response
			h := uri.NewHeaderDecoder(resp.Header)
			// Parse "X-Expires-After" header.
			{
				cfg := uri.HeaderParameterDecodingConfig{
					Name:    "X-Expires-After",
					Explode: false,
				}
				if err := func() error {
					if err := h.HasParam(cfg); err == nil {
						if err := h.DecodeParam(cfg, func(d uri.Decoder) error {
							var wrapperDotXExpiresAfterVal time.Time
							if err := func() error {
								val, err := d.DecodeValue()
								if err != nil {
									return err
								}

								c, err := conv.ToDateTime(val)
								if err != nil {
									return err
								}

								wrapperDotXExpiresAfterVal = c
								return nil
							}(); err != nil {
								return err
							}
							wrapper.XExpiresAfter.SetTo(wrapperDotXExpiresAfterVal)
							return nil
						}); err != nil {
							return err
						}
					}
					return nil
				}(); err != nil {
					return res, errors.Wrap(err, "parse X-Expires-After header")
				}
			}
			// Parse "X-Rate-Limit" header.
			{
				cfg := uri.HeaderParameterDecodingConfig{
					Name:    "X-Rate-Limit",
					Explode: false,
				}
				if err := func() error {
					if err := h.HasParam(cfg); err == nil {
						if err := h.DecodeParam(cfg, func(d uri.Decoder) error {
							var wrapperDotXRateLimitVal int32
							if err := func() error {
								val, err := d.DecodeValue()
								if err != nil {
									return err
								}

								c, err := conv.ToInt32(val)
								if err != nil {
									return err
								}

								wrapperDotXRateLimitVal = c
								return nil
							}(); err != nil {
								return err
							}
							wrapper.XRateLimit.SetTo(wrapperDotXRateLimitVal)
							return nil
						}); err != nil {
							return err
						}
					}
					return nil
				}(); err != nil {
					return res, errors.Wrap(err, "parse X-Rate-Limit header")
				}
			}
			return &wrapper, nil
		default:
			return res, validate.InvalidContentType(ct)
		}
	case 400:
		// Code 400.
		return &LoginUserBadRequest{}, nil
	}
	return res, validate.UnexpectedStatusCode(resp.StatusCode)
}

func decodeLogoutUserResponse(resp *http.Response) (res *LogoutUserDef, _ error) {
	// Default response.
	res, err := func() (res *LogoutUserDef, err error) {
		return &LogoutUserDef{
			StatusCode: resp.StatusCode,
		}, nil
	}()
	if err != nil {
		return res, errors.Wrapf(err, "default (code %d)", resp.StatusCode)
	}
	return res, nil
}

func decodeUpdateUserResponse(resp *http.Response) (res *UpdateUserDef, _ error) {
	// Default response.
	res, err := func() (res *UpdateUserDef, err error) {
		return &UpdateUserDef{
			StatusCode: resp.StatusCode,
		}, nil
	}()
	if err != nil {
		return res, errors.Wrapf(err, "default (code %d)", resp.StatusCode)
	}
	return res, nil
}
