// Code generated by ogen, DO NOT EDIT.
package api

type CreateUserReq interface {
	createUserReq()
}

type CreateUsersWithListInputRes interface {
	createUsersWithListInputRes()
}

type DeleteUserRes interface {
	deleteUserRes()
}

type GetUserByNameRes interface {
	getUserByNameRes()
}

type LoginUserRes interface {
	loginUserRes()
}

type UpdateUserReq interface {
	updateUserReq()
}
