name: Run project
run-name: Basic testing for main.go
on: [push]
jobs:
  compile_on_ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Install docker
        run: |
          sudo apt-get remove containerd.io
          sudo apt install docker.io docker-compose -y
      - name: Run the build process with Docker
        run: docker build -t builder .
      - name: Run image
        run: docker run --name test -t builder ls
      - name: Copy log file
        run: docker cp test:/log.txt ./log.txt
      - name: Upload Result
        uses: actions/upload-artifact@v4
        with:
          name: run_res
          path: /home/runner/work/KR/KR/log.txt

